/var/spool/slurm/job39624069/slurm_script: line 22: activate: No such file or directory
[I 2025-07-08 14:49:00.547 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-07-08 14:49:00.553 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-07-08 14:49:00.560 ServerApp] jupyterlab | extension was successfully linked.
[I 2025-07-08 14:49:00.567 ServerApp] notebook | extension was successfully linked.
[I 2025-07-08 14:49:01.023 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-07-08 14:49:01.063 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-07-08 14:49:01.066 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-07-08 14:49:01.068 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-07-08 14:49:01.074 LabApp] JupyterLab extension loaded from /ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/jupyterlab
[I 2025-07-08 14:49:01.074 LabApp] JupyterLab application directory is /ibex/user/rossom/conda-environments/myenv/share/jupyter/lab
[I 2025-07-08 14:49:01.074 LabApp] Extension Manager is 'pypi'.
[I 2025-07-08 14:49:01.091 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-07-08 14:49:01.098 ServerApp] notebook | extension was successfully loaded.
[I 2025-07-08 14:49:01.099 ServerApp] Serving notebooks from local directory: /ibex/user/rossom/devinterp
[I 2025-07-08 14:49:01.099 ServerApp] Jupyter Server 2.14.2 is running at:
[I 2025-07-08 14:49:01.099 ServerApp] http://dgpu501-14:10000/tree?token=d772649aa83ca03be35ad7666c4a2d9212c9536f60871f31
[I 2025-07-08 14:49:01.099 ServerApp]     http://127.0.0.1:10000/tree?token=d772649aa83ca03be35ad7666c4a2d9212c9536f60871f31
[I 2025-07-08 14:49:01.099 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2025-07-08 14:49:01.106 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/rossom/.local/share/jupyter/runtime/jpserver-2719527-open.html
    Or copy and paste one of these URLs:
        http://dgpu501-14:10000/tree?token=d772649aa83ca03be35ad7666c4a2d9212c9536f60871f31
        http://127.0.0.1:10000/tree?token=d772649aa83ca03be35ad7666c4a2d9212c9536f60871f31
[I 2025-07-08 14:49:01.200 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2025-07-08 14:49:14.846 ServerApp] 302 GET / (@10.109.65.13) 0.54ms
[I 2025-07-08 14:49:14.848 JupyterNotebookApp] 302 GET /tree? (@10.109.65.13) 0.63ms
[I 2025-07-08 14:49:15.896 ServerApp] 302 GET / (@10.109.65.13) 0.32ms
[I 2025-07-08 14:49:15.899 JupyterNotebookApp] 302 GET /tree? (@10.109.65.13) 0.44ms
[I 2025-07-08 14:49:23.709 ServerApp] 302 GET / (@10.109.65.13) 0.48ms
[I 2025-07-08 14:49:23.713 JupyterNotebookApp] 302 GET /tree? (@10.109.65.13) 0.48ms
[I 2025-07-08 14:49:23.784 ServerApp] Kernel started: 1ba6e57d-a8b0-4b0a-a256-6be396b00ae3
[I 2025-07-08 14:49:25.625 ServerApp] Connecting to kernel 1ba6e57d-a8b0-4b0a-a256-6be396b00ae3.
[I 2025-07-08 14:49:26.013 ServerApp] 302 GET / (@10.109.65.13) 2.12ms
[I 2025-07-08 14:49:26.030 JupyterNotebookApp] 302 GET /tree? (@10.109.65.13) 0.44ms
[W 2025-07-08 14:49:26.051 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-07-08 14:49:26.073 ServerApp] 403 GET /api/kernelspecs?1751975366049 (@10.109.65.13) 21.62ms referer=None
[W 2025-07-08 14:49:26.079 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-07-08 14:49:26.085 ServerApp] 403 GET /api/kernels?1751975366050 (@10.109.65.13) 7.41ms referer=None
[W 2025-07-08 14:49:26.090 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-07-08 14:49:26.095 ServerApp] 403 GET /api/kernels?1751975366051 (@10.109.65.13) 17.83ms referer=None
[W 2025-07-08 14:49:26.100 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-07-08 14:49:26.101 ServerApp] 403 GET /api/sessions?1751975366051 (@10.109.65.13) 22.67ms referer=None
[W 2025-07-08 14:49:26.101 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-07-08 14:49:26.102 ServerApp] 403 GET /api/kernelspecs?1751975366074 (@10.109.65.13) 23.44ms referer=None
[I 2025-07-08 14:49:26.107 ServerApp] 302 GET / (@10.109.65.13) 0.33ms
[I 2025-07-08 14:49:26.137 JupyterNotebookApp] 302 GET /tree? (@10.109.65.13) 0.42ms
[W 2025-07-08 14:49:26.148 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-07-08 14:49:26.151 ServerApp] 403 GET /api/kernelspecs?1751975366142 (@10.109.65.13) 3.58ms referer=None
[W 2025-07-08 14:49:26.157 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-07-08 14:49:26.159 ServerApp] 403 GET /api/kernels?1751975366144 (@10.109.65.13) 2.97ms referer=None
[W 2025-07-08 14:49:26.160 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-07-08 14:49:26.161 ServerApp] 403 GET /api/kernels?1751975366147 (@10.109.65.13) 4.38ms referer=None
[W 2025-07-08 14:49:26.162 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-07-08 14:49:26.163 ServerApp] 403 GET /api/kernelspecs?1751975366155 (@10.109.65.13) 1.16ms referer=None
[W 2025-07-08 14:49:26.163 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/ibex/user/rossom/conda-environments/myenv/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2025-07-08 14:49:26.164 ServerApp] 403 GET /api/sessions?1751975366151 (@10.109.65.13) 1.90ms referer=None
[W 2025-07-08 14:49:29.455 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@10.109.65.13) 7.38ms referer=None
[I 2025-07-08 14:49:29.457 ServerApp] 302 GET / (@10.109.65.13) 0.33ms
[I 2025-07-08 14:49:29.460 JupyterNotebookApp] 302 GET /tree? (@10.109.65.13) 0.42ms
[W 2025-07-08 14:49:29.543 ServerApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js (@10.109.65.13) 0.84ms referer=None
